### ISSUE TITLE
How to callback java when native crashed

### ISSUE THREAD

**Issue by huangjk1225** [SummerOak/CrashSDK#1]
hello @SummerOak ，when I use this project， I found it could‘t callback java when native crashed，could you help me？

Look forward to your reply

**Comment by SummerOak** [comment]
@huangjk1225  We can not call java method directly in signal handler,  but you can do it in other thread, usually you can created that thread while registering the signal handler and waiting event from crash thread; It is a known issue: https://issuetracker.google.com/issues/37035211

**Comment by huangjk1225** [comment]
hello @SummerOak ，We find that，when libcrashsdk.so crashes in the inside and cannot be callback to java，after we add another so，such as a.so，into the project，the callback happens when it crashes。Why? Does it have anything to do with creating new threads?

**Comment by huangjk1225** [comment]
And can you speak Chinese？
